### ISSUE TITLE
CSS Clean - exception

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#165]
Do not clean the `.loading` class. This class is added in the form submit button on click to show an animation. Add exception to the `ignore` - along the lines of:

```js
new RegExp('\.loading*(.)\S+')
```

**Comment by nathakits** [comment]
I tested the `('\.loading*(.)\S+')` regex in sublime text to see if it could find the class. But it turns out it didn't find `.loading` class and only found `.loading:after` and `.loading:before`. When I did `gulp build`, there were no `.loading` classes in the `main.css` at all.

 So i tried `^.loading.*` regex instead and everything appears to be in the `main.css` and also appears to be working in the `localhost` test (throttled GPRS network to see the animation). So the css clean in this PR include `^.loading.*` regex instead.

PR - https://github.com/pupil-labs/pupil-labs-website/pull/166

**Comment by willpatera** [comment]
fixed with #166
